name: 'Run ROOT CERN Script'
description: 'Run a ROOT CERN script'
inputs:
  root_script:
    description: 'The ROOT CERN script to run'
    required: true
  output_file:
    description: 'The output file to check'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup ROOT CERN
      uses: ./setup-root-cern

    - name: Run ROOT CERN Script
      run: chmod +x ./script.sh && ./script.sh ${{ inputs.root_script }} ${{ inputs.output_file }}
      shell: bash
