name: 'Setup ROOT CERN'
description: 'Set up ROOT CERN environment'
runs:
  using: 'composite'
  steps:
    - name: Download ROOT CERN
      run: wget https://github.com/MohamedElashri/ROOT/releases/download/ubuntu/root_v6.28.04_Ubuntu_20.04.zip
      shell: bash

    - name: Unzip and Install ROOT CERN
      run: |
        sudo unzip root_v6.28.04_Ubuntu_20.04.zip -d /usr/local
        sudo mv /usr/local/root_build /usr/local/root
      shell: bash

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git dpkg-dev cmake g++ gcc binutils libx11-dev libxpm-dev libxft-dev libxext-dev tar gfortran subversion  
      shell: bash
